// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecantosApi.Infra;

#nullable disable

namespace RecantosApi.Migrations
{
    [DbContext(typeof(RecantoDbContext))]
    [Migration("20241118181530_AddCasaAndBlocos")]
    partial class AddCasaAndBlocos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RecantosApi.Models.Residente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CasaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.ToTable("Residentes");
                });

            modelBuilder.Entity("api.models.Bloco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blocos");
                });

            modelBuilder.Entity("api.models.Casa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BlocoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("RecantosApi.Models.Residente", b =>
                {
                    b.HasOne("api.models.Casa", null)
                        .WithMany("Residentes")
                        .HasForeignKey("CasaId");
                });

            modelBuilder.Entity("api.models.Casa", b =>
                {
                    b.HasOne("api.models.Bloco", null)
                        .WithMany("Casas")
                        .HasForeignKey("BlocoId");
                });

            modelBuilder.Entity("api.models.Bloco", b =>
                {
                    b.Navigation("Casas");
                });

            modelBuilder.Entity("api.models.Casa", b =>
                {
                    b.Navigation("Residentes");
                });
#pragma warning restore 612, 618
        }
    }
}
